export const GET_DATA_REQUEST_ACTION = "DOG_PICTURE::GET_DATA_REQUEST_ACTION";

export const GET_DATA_SUCCESS_ACTION = "DOG_PICTURE::GET_DATA_SUCCESS_ACTION";

export const GET_DATA_ERROR_ACTION = "DOG_PICTURE::GET_DATA_ERROR_ACTION";

export const GET_DATA_FINALLY_ACTION = "DOG_PICTURE::GET_DATA_FINALLY_ACTION";
