export const ADD_EMAIL_ACTION = "AUTHENTICATED::ADD_EMAIL_ACTION";

export const ADD_PASSWORD_ACTION = "AUTHENTICATED::ADD_PASSWORD_ACTION";

export const SUBMIT_ERROR_ACTION = "AUTHENTICATED::SUBMIT_ERROR_ACTION";

export const AUTHED_ACTION = "AUTHENTICATED::AUTHED_ACTION";

export const NOT_AUTHED_ACTION = "AUTHENTICATED::NOT_AUTHED_ACTION";

export const CURRENT_USER_ACTION = "AUTHENTICATED::CURRENT_USER_ACTION";
